routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\ProdukController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('dashboard.produk.index');
})->name('home');

// get data from api
Route::name('produk.')->group(function () {
    Route::get('/getData', [ProdukController::class, 'getData'])->name('getData');
    Route::get('/produk', [ProdukController::class, 'index'])->name('index');
    Route::post('/produk/store', [ProdukController::class, 'store'])->name('store');
    Route::get('/produk/{id}/edit', [ProdukController::class, 'edit'])->name('edit');
    Route::patch('/produk/update/{id}', [ProdukController::class, 'update'])->name('update');
    Route::get('/produk/getKategoriStatus', [ProdukController::class, 'getKategoriStatus'])->name('getKategoriStatus');
    Route::delete('/produk/delete/{id}', [ProdukController::class, 'destroy'])->name('delete');
});

app/Models/Produk.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Produk extends Model
{
    use HasFactory;

    protected $guarded = ['id_produk'];

    public function kategori(){
        return $this->belongsTo(Kategori::class, 'kategori_id', 'id_kategori');
    }
}

app/Http/Controllers/ProdukController.php
<?php

namespace App\Http\Controllers;

use App\Models\Produk;
use App\Models\Kategori;
use App\Models\Status;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Validator;
use Yajra\DataTables\DataTables;

class ProdukController extends Controller
{
    public function getData() {
        $pass = md5('bisacoding-' . date('d-m-y'));
        $client = new \GuzzleHttp\Client();
        $response = $client->post(
            'https://recruitment.fastprint.co.id/tes/api_tes_programmer',
            array(
                'form_params' => array(
                    'username' => 'tesprogrammer111023C12',
                    'password' => $pass
                )
            )
        );

        //get data
        $data = json_decode($response->getBody());

        //save to database
        foreach($data->data as $key => $value) {
            $produk = new Produk;
            $produk->id_produk = $value->id_produk;
            $produk->nama_produk = $value->nama_produk;
            $produk->harga = $value->harga;
            $produk->kategori_id = $value->kategori;
            $produk->status_id = $value->status;
            $produk->save();
        }

        return redirect()->route('home');
    }

    public function index()
    {
        if (request()->ajax()) {
            $data = Produk::where('status_id', 1)->orderBy('id_produk', 'desc')->get();
            return DataTables::of($data)
              ->addIndexColumn()
              ->addColumn('action', function ($produk) {
                    return '
                        <div class="d-flex">
                          <button class="btn btn-warning btn-sm mx-1 edit-data" data-id="' . $produk->id_produk . '" type="button"><i class="bi bi-pencil"></i></button>
                          <button class="btn btn-danger btn-sm delete-data" data-id="' . $produk->id_produk . '" type="button"><i class="bi bi-trash"></i></button>
                        </div>
                        ';
                
              })
              ->editColumn('harga', function ($produk) {
                return 'Rp. ' . number_format($produk->harga, 0, ',', '.');
              })
              ->editColumn('status_id', function ($produk) {
                if($produk->status_id == 1) {
                    return "bisa dijual";
                } else {
                    return "tidak bisa dijual";
                }
              })
              ->editColumn('kategori_id', function ($produk) {
                return $produk->kategori->nama_kategori;
              })
              ->rawColumns(['action'])
              ->make('true');
        }

        // return redirect()->route('home);
    }

    public function getKategoriStatus() {
        if(request()->ajax()) {
            try {
                $kategories = Kategori::all();
                $statuses = Status::all();

                return ['status' => 200, 'kategories' => $kategories, 'statuses' => $statuses];
            } catch (\Throwable $th) {
                return ['status' => 500, 'message' => 'Gagal mengambil data!'];
            }
        }
    }

    public function store(Request $request)
    {
        if ($request->ajax()) {
            $rules = [
                'nama_produk' => 'required',
                'harga' => 'required',
                'kategori_id' => 'required',
                'status_id' => 'required',
            ];

            $messages = [
                'required' => ':attribute harus diisi',
            ];

            $aliases = [
                'name' => 'Nama produk',
                'harga' => 'Harga produk',
                'kategori_id' => 'Kategori',
                'status_id' => 'Status',
            ];

            $validator = Validator::make($request->all(), $rules, $messages, $aliases);

            if ($validator->fails()) {
                return ['status' => 422, 'validation' => $validator->getMessageBag()];
            }

            try {

                DB::transaction(function () use ($validator, $request) {
                    $validated = $validator->validated();
                    $barang = Produk::create($validated);
                });

                return ['status' => 200, 'message' => 'Data berhasil ditambahkan'];
            } catch (\Throwable $th) {
                return ['status' => 500, 'message' => 'Data gagal ditambahkan' . $th->getMessage()];
            }
        }
    }

    public function edit(Request $request, $id)
    {
        if ($request->ajax()) {
            try {
                $produk = Produk::where('id_produk', $id)->first();
                $kategories = Kategori::all();
                $statuses = Status::all();

                return ['status' => 200, 'produk' => $produk, 'kategories' => $kategories, 'statuses' => $statuses];
            } catch (\Throwable $th) {
                return ['status' => 500, 'message' => 'Gagal mengambil data!'];
            }
        }
    }

    public function update(Request $request, $id)
    {
        if ($request->ajax()) {
            // $produk = Produk::where('id_produk', $id)->first();

            $rules = [
                'nama_produk' => 'required',
                'harga' => 'required',
                'kategori_id' => 'required',
                'status_id' => 'required',
            ];

            $messages = [
                'required' => ':attribute harus diisi',
            ];

            $aliases = [
                'name' => 'Nama produk',
                'harga' => 'Harga produk',
                'kategori_id' => 'Kategori',
                'status_id' => 'Status',
            ];

            $validator = Validator::make($request->all(), $rules, $messages, $aliases);

            if ($validator->fails()) {
                return ['status' => 422, 'validation' => $validator->getMessageBag()];
            }

            try {
                $validated = $validator->validated();
                Produk::where('id_produk', $id)->update([
                    'nama_produk' => $validated['nama_produk'],
                    'harga' => $validated['harga'],
                    'kategori_id' => $validated['kategori_id'],
                    'status_id' => $validated['status_id'],
                ]);

                return ['status' => 200, 'message' => 'Data berhasil diubah'];
            } catch (\Throwable $th) {
                return ['status' => 500, 'message' => 'Data gagal diubah' . $th->getMessage()];
            }
        }
    }

    public function destroy($id)
    {
        if (request()->ajax()) {
            try {
                Produk::where('id_produk', $id)->delete();
              return ['status' => 200, 'message' => 'Data berhasil dihapus'];
            } catch (\Throwable $th) {
              return ['status' => 500, 'message' => 'Data gagal dihapus'];
            }
        }
    }
}

resources/views/dashboard/produk/index.blade.php
@extends('layouts.dashboard-app')
@section('content')
<main id="main" class="main content">

    <div class="pagetitle">
      <h1>Produk</h1>
      <nav>
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="{{ route('home') }}">Home</a></li>
          <li class="breadcrumb-item active">Persediaan Produk</li>
        </ol>
      </nav>
    </div><!-- End Page Title -->

    <section class="section">

			<div class="row mb-3">
				<!-- <div class="col-12 col-md-6">
					<div class="p-2 rounded bg-white shadow-sm">
						<div class="row">
							<label for="" class="col-sm-3 col-form-label">Filter Status</label>
							<div class="col-sm-9">
								<select class="form-select select-status" aria-label="Default select example">
									<option value="bisa dijual" selected>Bisa dijual</option>
									<option value="tidak bisa dijual">Tidak bisa dijual</option>
								</select>
							</div>
						</div>
					</div>
				</div> -->

				<div class="col">
					<div class="d-flex justify-content-end p-2">
						{{-- <a class="btn btn-success me-2" href="{{ route('produk.getData') }}" id="get-produk">
								<i class="bi bi-box-arrow-down me-1"></i>
								GET data
						</a> --}}
	
						<a class="btn btn-primary" href="#" id="add-produk">
								<i class="bi bi-plus-square me-1"></i>
								Tambah
						</a>
					</div>
				</div>
			</div>

      <div class="row">
        <div class="col">

          <div class="card">
            <div class="card-body">
              <h5 class="card-title">Persediaan Produk</h5>

              <!-- Default Table -->
              <table class="table" id="datatable-produk">
                <thead>
                  <tr>
                    <th scope="col">#</th>
                    <th scope="col">Nama</th>
                    <th scope="col">Kategori</th>
                    <th scope="col">Harga</th>
                    <th scope="col">Status</th>
                    <th scope="col">Aksi</th>
                  </tr>
                </thead>
                <tbody>
                </tbody>
              </table>
              <!-- End Default Table Example -->
            </div>
          </div>

        </div>
      </div>
    </section>

  </main>
@endsection

@section('script')
<script src="{{ asset('assets/module/produk/app.js') }}" type="module"></script>
@endsection